### ISSUE TITLE
Screenshots are missing in report

### ISSUE THREAD

**Issue by pvimalmec** [serenity-js/protractor-cucumber-framework-demo#14]
Hi, Im missing screenshots in the report.! Could you please help me how to get screenshots in the report?

**Comment by jan-molak** [comment]
Hi @pvimalmec! Please note that screenshots will be taken automatically only when the tests are using the [Screenplay Pattern](https://serenity-js.org/handbook/thinking-in-serenity-js/screenplay-pattern.html).

Is this how you have them set up?

**Comment by pvimalmec** [comment]
I just used this project protractor-cucumber-framework-demo to how ots working. Hope this project of yours is not based on screenplay pattern. How should I implement screen play pattern in protractor-cucumber-framework?

**Comment by jan-molak** [comment]
Hey @pvimalmec - it's fairly simple, all the [configuration](https://serenity-js.org/modules/protractor/) is all done for you already in this repo. 
There's plenty of reference implementations at https://github.com/serenity-js, the one for [TodoMVC](https://github.com/serenity-js/todomvc-demo) might be a good starting point.
You'll also find the API docs at https://serenity-js.org/modules/protractor/

And if you have any questions, feel free to ask them on [Serenity/JS Community chat channel](https://gitter.im/serenity-js/Lobby)

Hope this helps!
